CREATE TABLE IF NOT EXISTS sync_task_checkpoint (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    task_name VARCHAR(64) NOT NULL COMMENT '任务名',
    chain_id BIGINT NOT NULL COMMENT '链ID',
    contract_address VARCHAR(42) NOT NULL COMMENT '合约地址',
    start_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '起始区块',
    last_scanned_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最新已入库区块',
    last_safe_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本轮安全区块=最新区块-延迟块数',
    delay_blocks INT UNSIGNED NOT NULL DEFAULT 6 COMMENT '延迟确认块数',
    status VARCHAR(16) NOT NULL DEFAULT 'INIT' COMMENT 'INIT/RUNNING/IDLE',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_task_chain_contract (task_name, chain_id, contract_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='扫链断点表';

CREATE TABLE IF NOT EXISTS akapledge_event_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    chain_id BIGINT NOT NULL COMMENT '链ID',
    contract_address VARCHAR(42) NOT NULL COMMENT '合约地址',
    block_number BIGINT UNSIGNED NOT NULL COMMENT '区块号',
    block_hash VARCHAR(66) NOT NULL COMMENT '区块hash',
    tx_hash VARCHAR(66) NOT NULL COMMENT '交易hash',
    tx_index INT UNSIGNED NOT NULL COMMENT '交易索引',
    log_index INT UNSIGNED NOT NULL COMMENT '日志索引',
    event_name VARCHAR(64) NOT NULL COMMENT '事件名',
    pool_id VARCHAR(78) NOT NULL DEFAULT '' COMMENT '池ID',
    user_address VARCHAR(42) NOT NULL DEFAULT '' COMMENT '用户地址',
    topic0 VARCHAR(66) NOT NULL COMMENT '事件签名',
    payload_json JSON NOT NULL COMMENT '完整事件json',
    removed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否被重组移除',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_tx_log (tx_hash, log_index),
    KEY idx_contract_block (chain_id, contract_address, block_number),
    KEY idx_pool_event (pool_id, event_name),
    KEY idx_user_event (user_address, event_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='原始事件流水表';

CREATE TABLE IF NOT EXISTS akapledge_pool (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    chain_id BIGINT NOT NULL COMMENT '链ID',
    contract_address VARCHAR(42) NOT NULL COMMENT '合约地址',
    pool_id VARCHAR(78) NOT NULL COMMENT '池ID',
    admin_address VARCHAR(42) NOT NULL DEFAULT '' COMMENT '创建管理员',
    lend_token VARCHAR(42) NOT NULL DEFAULT '' COMMENT '出借token',
    collateral_token VARCHAR(42) NOT NULL DEFAULT '' COMMENT '抵押token',
    stage VARCHAR(32) NOT NULL DEFAULT 'MATCH' COMMENT '池阶段',
    settle_time BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '撮合截止时间',
    execution_end_time BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '执行截止时间',
    fixed_interest_rate_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '固定利率bps',
    collateral_ratio_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '抵押率bps',
    liquidation_threshold_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '清算阈值bps',
    protocol_fee_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '协议费bps',
    slippage_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '滑点bps',
    total_lend_deposited VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '总出借金额',
    total_collateral_deposited VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '总抵押金额',
    matched_principal VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '撮合本金',
    used_collateral_amount VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '占用抵押物',
    unmatched_lend_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '未撮合出借',
    unmatched_collateral_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '未撮合抵押',
    stable_loan_paid_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '已放款总额',
    stable_lend_refund_paid_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '已退还出借总额',
    collateral_borrow_refund_paid_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '已退还抵押总额',
    latest_collateral_value_stable VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '最近一次健康检查的抵押价值',
    latest_debt_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '最近一次健康检查的债务总额',
    latest_ratio_bps VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '最近一次健康检查抵押率',
    latest_health_result TINYINT(1) NOT NULL DEFAULT 0 COMMENT '最近一次健康检查是否安全',
    stable_to_lenders_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '结算后分给出借人的稳定币总额',
    stable_to_borrowers_surplus_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '结算后分给借款人的稳定币盈余',
    collateral_to_borrowers_total VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '结算后返给借款人的抵押物总量',
    finish_collateral_sold VARCHAR(78) NOT NULL DEFAULT '0' COMMENT 'finish/liquidation卖出的抵押物',
    finish_stable_balance_before VARCHAR(78) NOT NULL DEFAULT '0' COMMENT 'finish/liquidation前稳定币余额',
    finish_stable_balance_after VARCHAR(78) NOT NULL DEFAULT '0' COMMENT 'finish/liquidation后稳定币余额',
    finish_block_number BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'finish/liquidation所在区块',
    last_event_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后事件区块',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_chain_contract_pool (chain_id, contract_address, pool_id),
    KEY idx_stage_settle (stage, settle_time),
    KEY idx_last_event_block (last_event_block)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运营池汇总表';

CREATE TABLE IF NOT EXISTS akapledge_lender_position (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    chain_id BIGINT NOT NULL COMMENT '链ID',
    contract_address VARCHAR(42) NOT NULL COMMENT '合约地址',
    pool_id VARCHAR(78) NOT NULL COMMENT '池ID',
    lender_address VARCHAR(42) NOT NULL COMMENT '出借人地址',
    lend_deposited VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '累计出借',
    lend_refunded VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '累计退款',
    matched_principal_share VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '撮合本金份额',
    sp_minted VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '铸造SP数量',
    sp_burned VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '销毁SP数量',
    stable_withdrawn VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '提取稳定币',
    last_event_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后事件区块',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_chain_contract_pool_lender (chain_id, contract_address, pool_id, lender_address),
    KEY idx_pool_lender (pool_id, lender_address),
    KEY idx_lender (lender_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出借人运营仓位表';

CREATE TABLE IF NOT EXISTS akapledge_borrower_position (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    chain_id BIGINT NOT NULL COMMENT '链ID',
    contract_address VARCHAR(42) NOT NULL COMMENT '合约地址',
    pool_id VARCHAR(78) NOT NULL COMMENT '池ID',
    borrower_address VARCHAR(42) NOT NULL COMMENT '借款人地址',
    collateral_deposited VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '累计抵押',
    collateral_refunded VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '累计退还抵押',
    collateral_used_share VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '占用抵押份额',
    jp_minted VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '铸造JP数量',
    jp_burned VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '销毁JP数量',
    loan_paid_amount VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '累计借到的稳定币',
    collateral_withdrawn VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '提回抵押物',
    stable_surplus_withdrawn VARCHAR(78) NOT NULL DEFAULT '0' COMMENT '提回稳定币盈余',
    last_event_block BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后事件区块',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_chain_contract_pool_borrower (chain_id, contract_address, pool_id, borrower_address),
    KEY idx_pool_borrower (pool_id, borrower_address),
    KEY idx_borrower (borrower_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='借款人运营仓位表';
