package abi

const AkaPledgeABI = `[
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"admin","type":"address"},{"indexed":false,"internalType":"address","name":"lendToken","type":"address"},{"indexed":false,"internalType":"address","name":"collateralToken","type":"address"},{"indexed":false,"internalType":"uint256","name":"settleTime","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"executionEndTime","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"fixedInterestRateBps","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralRatioBps","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"liquidationThresholdBps","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"protocolFeeBps","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"slippageBps","type":"uint256"}],"name":"PoolCreated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":false,"internalType":"uint8","name":"fromStage","type":"uint8"},{"indexed":false,"internalType":"uint8","name":"toStage","type":"uint8"}],"name":"PoolStageUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"lender","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"LendDeposited","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"borrower","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"BorrowDeposited","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"totalLendDeposited","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"totalCollateralDeposited","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"matchedPrincipal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"usedCollateralAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"unmatchedLendTotal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"unmatchedCollateralTotal","type":"uint256"}],"name":"Settled","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"lender","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"LenderRefunded","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"lender","type":"address"},{"indexed":false,"internalType":"uint256","name":"matchedPrincipalShare","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"spAmountMinted","type":"uint256"}],"name":"LenderClaimed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"borrower","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"BorrowerRefunded","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"borrower","type":"address"},{"indexed":false,"internalType":"uint256","name":"collateralUsedShare","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"loanPaidAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"jpAmountMinted","type":"uint256"}],"name":"BorrowerClaimed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralValueStable","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"debtTotal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"ratioBps","type":"uint256"},{"indexed":false,"internalType":"bool","name":"sufficient","type":"bool"}],"name":"HealthChecked","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralBalanceBeforeSwap","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralSold","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableBalanceBefore","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableBalanceAfter","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableToLendersTotal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableToBorrowersSurplusTotal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralToBorrowersTotal","type":"uint256"}],"name":"Finished","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralBalanceBeforeSwap","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralSold","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableBalanceBefore","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableBalanceAfter","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableToLendersTotal","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableToBorrowersSurplusTotal","type":"uint256"}],"name":"Liquidated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"lender","type":"address"},{"indexed":false,"internalType":"uint256","name":"spBurned","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableAmount","type":"uint256"}],"name":"LenderWithdrawn","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"poolId","type":"uint256"},{"indexed":true,"internalType":"address","name":"borrower","type":"address"},{"indexed":false,"internalType":"uint256","name":"jpBurned","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"collateralAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"stableSurplusAmount","type":"uint256"}],"name":"BorrowerWithdrawn","type":"event"}
]`
